// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clothes.sql

package sqlc

import (
	"context"
)

const getOneByCategoryStyleWeather = `-- name: GetOneByCategoryStyleWeather :one
SELECT id, name, price, color, category, style, weather, created_at, updated_at FROM clothes
WHERE category = $1
  AND style = $2
  AND weather = $3
ORDER BY id
LIMIT 1
`

type GetOneByCategoryStyleWeatherParams struct {
	Category string
	Style    string
	Weather  string
}

func (q *Queries) GetOneByCategoryStyleWeather(ctx context.Context, arg GetOneByCategoryStyleWeatherParams) (Clothe, error) {
	row := q.db.QueryRow(ctx, getOneByCategoryStyleWeather, arg.Category, arg.Style, arg.Weather)
	var i Clothe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Color,
		&i.Category,
		&i.Style,
		&i.Weather,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
