// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Clothe struct {
	ID        int64
	Name      string
	Price     pgtype.Numeric
	Color     string
	Category  string
	Style     string
	Weather   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
